### ISSUE TITLE
主站的搜索机制好像有点问题

### ISSUE THREAD

**Issue by LingrenKong** [cosname/cosx.org#1085]
有些文章好像搜不到？

比如“R Markdown 入门教程“ 就不行，主站的位置是：https://github.com/cosname/cosx.org/blob/master/content/post/2021-04-10-rmarkdown-introduction.md

**Comment by tcgriffith** [comment]
大概率是索引没更新

**Comment by CyrusYip** [comment]
确实搜不到，直接谷歌搜「R Markdown 入门教程 site:cosx.org」就可以。

**Comment by nanxstats** [comment]
索引确实需要更新了，最近三年的文章都不会在搜索结果中出现。猜测可能是因为某种原因 Travis CI 的流程并没有正常运行。cc @yihui @Lchiffon 

目前最后一篇被索引的文章是 <https://cosx.org/2020/09/covid19-bulletin-board/> (2020-09-14)

Related: https://github.com/cosname/cosx.org/issues/874#issuecomment-577901794

**Comment by yihui** [comment]
Travis 几年前从 .org 迁移 .com 的时候把旧库都停了。@Lchiffon 可能没有迁移。

现在需要有人把 .travis.yml 用 Github Action 改写一下。

**Comment by yufree** [comment]
我先贴一个ChatGPT转换版本，好像那边仓库没权限，需要知道环境变量`AL_VALUE`、`GITHUB_ID` 和 `GITHUB_SECRET`。

```yaml
name: Node.js CI

on:
  push:
    branches:
      - master  # 触发分支可以根据需要进行调整

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 6.0.0

    - name: Install global packages
      run: |
        npm install gulp-cli -g
        npm install babel-cli -g

    - name: Install dependencies
      run: npm install

    - name: Clone repository
      run: git clone https://github.com/cosname/cosx.org.git docs

    - name: Prepare environment
      run: |
        echo "ALGOLIA_API_SECRET=${{ secrets.AL_VALUE }}" >> .env
        echo "GITHUB_ID=${{ secrets.GITHUB_ID }}" >> .env
        echo "GITHUB_SECRET=${{ secrets.GITHUB_SECRET }}" >> .env
        curday=$(date +%Y-%m-%d)
        echo "var curday='${curday}'" >> gulpfile.babel.js2
        cat gulpfile.babel.js >> gulpfile.babel.js2
        rm gulpfile.babel.js
        mv gulpfile.babel.js2 gulpfile.babel.js

    - name: Build and test
      run: |
        gulp index

```
