### ISSUE TITLE
一个想法：根目录下维护一个 authors_info.yaml

### ISSUE THREAD

**Issue by fyears** [cosname/cosx.org#226]
根目录下维护一个 authors_info.yaml，渲染文章的时候，hugo 自动选取对应的作者信息，并且把文本添加到文章底部“关于作者”的位置（和 tag 并列）。

这样就可以自动生成关于作者等信息，所有文章自动更新作者信息。

电子邮件支持 base64。

（其实就是用静态化信息山寨 wp 对应的功能。）

```yaml
# authors_info.yaml

John Smith:
    github: john
    description: some nobody
    email: a@example.org

Alex Doe:
    github: alex
    blog: https://www.example.com
    email: YUBleGFtcGxlLmNvbQ==
```
