### ISSUE TITLE
页面导航条变大些

### ISSUE THREAD

**Issue by fyears** [cosname/cosx.org#628]
![_20170717220218](https://user-images.githubusercontent.com/1142836/28271617-a07dd9a0-6b3b-11e7-96d8-84fee328a638.png)

页面底部的这个导航条如此之小，无论电脑的鼠标还是平板手机的手指都很难定位和点击。~~“能变得大气些吗”~~ 这个是 bug 还是 feature？

最简单的做法是

```css
ul.pagination {
  font-size: 1.5rem;
}
```

可是这样破坏了整个页面的设计感，和页面头部的

```
统计之都    2017/07/17    40 / 40
```

大小不一致了。
